//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoanModule.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Broker
    {
        public int BrokerID { get; set; }
        public string BrokerFirst { get; set; }
        public string BrokerLast { get; set; }
        public string BrokerPhone { get; set; }
        public string BrokerEmail { get; set; }
        public string ReferredBy { get; set; }
        public string County { get; set; }
        public Nullable<bool> OptIn { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public string Position { get; set; }
        public string NMLSCertified { get; set; }
        public string NMLSNumber { get; set; }
        public string StatesLicensed { get; set; }
        public string StateLicenses { get; set; }
        public string RealtorsRef { get; set; }
        public string Notes { get; set; }
        public Nullable<System.DateTime> LeadDate { get; set; }
        public string FormName { get; set; }
    }
}
