//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoanModule.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int EmpID { get; set; }
        public string EmpFirst { get; set; }
        public string EmpLast { get; set; }
        public string EmpEmail { get; set; }
        public string EmpTitle { get; set; }
        public Nullable<int> EmpNMLS { get; set; }
        public string EmpPhone { get; set; }
        public string EmpMobile { get; set; }
        public string EmpFax { get; set; }
        public byte[] EmpLinkedIn { get; set; }
        public string EmpFacebook { get; set; }
        public string EmpPhoto { get; set; }
    }
}
