//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoanModule.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MWFUser
    {
        public int UserId { get; set; }
        public string Id { get; set; }
        public string UserFirst { get; set; }
        public string UserLast { get; set; }
        public string UserFullName { get; set; }
        public string UserTitle { get; set; }
        public Nullable<int> UserNMLS { get; set; }
        public string UserPhone { get; set; }
        public string UserMobile { get; set; }
        public string UserFax { get; set; }
        public string UserLinkedIn { get; set; }
        public string UserFacebook { get; set; }
        public string UserPhoto { get; set; }
        public string UserBranch { get; set; }
        public string UserEmail { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
