//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoanModule.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewLead
    {
        public NewLead()
        {
            this.LeadNotes = new HashSet<LeadNote>();
        }
    
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string LoanType { get; set; }
        public string County { get; set; }
        public string ReferredBy { get; set; }
        public string LoanAgent { get; set; }
        public System.DateTime LeadDate { get; set; }
        public bool OptIn { get; set; }
    
        public virtual ICollection<LeadNote> LeadNotes { get; set; }
    }
}
