//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoanModule.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Realtor
    {
        public int RealtorID { get; set; }
        public string RealtorFirst { get; set; }
        public string RealtorLast { get; set; }
        public string RealtorPhone { get; set; }
        public string RealtorEmail { get; set; }
        public string ReferredBy { get; set; }
        public string County { get; set; }
        public string LoanAgent { get; set; }
        public Nullable<bool> OptIn { get; set; }
        public string Company { get; set; }
        public string Website { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public string WorkPhone { get; set; }
        public string Fax { get; set; }
        public string JobTitle { get; set; }
        public string ManageRealtors { get; set; }
        public string NoRealtors { get; set; }
        public string Farm1 { get; set; }
        public string Farm2 { get; set; }
        public string Farm3 { get; set; }
        public string Farm4 { get; set; }
        public string Farm5 { get; set; }
        public string LinkedIn { get; set; }
        public string Facebook { get; set; }
        public string BRELicense { get; set; }
        public string Notes { get; set; }
        public Nullable<System.DateTime> LeadDate { get; set; }
        public string FormName { get; set; }
    }
}
